Added MAYK to the food menu.
wilmaplus/foodmenu pull request #3
Opened 2022-01-31 19:55 UTC by zeriaxdev

I added MAYK (Maunulan yhteiskoulu) to the list, as it is my current school.
I'd really love to see it in production! Thank you!

Changes:
```
        modified:   README.md
        new file:   src/handlers/mayk.ts
        modified:   src/main.ts
        new file:   src/parsers/mayk.ts
```

2022-01-31 23:27 UTC, developerfromjokela commented
Thanks for the PR!

I'll have a look tomorrow, and possibly deploy to production (if it makes through to merging) this week.

2022-02-01 07:31 UTC, zeriaxdev commented
Thanks! I hope nothing breaks 😂

2022-02-05 08:55 UTC, developerfromjokela commented
Seems like it doesn't work correctly? Currently it shows empty response, despite the mayk website containing the food menu.

![image](https://user-images.githubusercontent.com/40487414/152635294-19e78726-dcdc-4fc7-af44-08a548aa59e5.png)

![image](https://user-images.githubusercontent.com/40487414/152635295-9fa63331-219a-4db3-9584-98d1f1a85089.png)

2022-02-05 09:01 UTC, developerfromjokela requested changes
Parser needs enhancements for date handling.

2022-02-05 09:01 UTC, developerfromjokela commented on src/parsers/mayk.ts
> +                    currentDayDate = moment(regexResult[0], "DD.MM.YYYY").startOf('day');
Food menu supplies a week name (maanantai,tiistai,etc), in `.ruoka-header-pvm`.
The way to get real date is to first get `ruokalista-viikko` value, in order to get a date in return.
With that date, just change the week day according to `.ruoka-header-pvm`.

But these food menus are often unpredictable, most of them written by hand, thus they sometimes change unexpectedly.

2022-02-05 09:19 UTC, zeriaxdev commented on src/parsers/mayk.ts
> +                    currentDayDate = moment(regexResult[0], "DD.MM.YYYY").startOf('day');
I'm very sorry for this issues...

> But these food menus are often unpredictable, most of them written by hand, thus they sometimes change unexpectedly.

Sadly, it's true. Sometimes date are just missing.

2022-02-10 21:18 UTC, developerfromjokela commented on src/parsers/mayk.ts
> +                    currentDayDate = moment(regexResult[0], "DD.MM.YYYY").startOf('day');
If you could implement a simple check, if it contains the week instead, and take appropriate action?

2022-04-25 06:45 UTC, developerfromjokela commented
@zeriaxdev should I close this PR or you're still working on this?

2022-04-25 12:54 UTC, zeriaxdev commented
> @zeriaxdev should I close this PR or you're still working on this?

I think you should. I'm not currently working on this, and the website itself has some issues.

2022-05-02 12:37 UTC, closed without merging